### ISSUE TITLE
Dependency on `Spatie/Enum/Enum`

### ISSUE THREAD

**Issue by scaabel** [spatie/laravel-typescript-transformer#12]
As PHP 8.1 has support for Enums, I don't see why this package needs to be dependant on another package.
I am currently trying to run `php artisan typescript:transform`, but I am getting this error.
Are there any workaround that I can implement to temporarily avoid this issue?

![image](https://user-images.githubusercontent.com/63094088/145375364-f588c491-66b1-4f87-ae10-7682c670b427.png)

**Comment by rubenvanassche** [comment]
Hi @scaabel,

It is required for tests, that's why it is in the require-dev section. You could omit the enum package by removing the spatie enum transformer from your config. We're currently not removing this package a) because it has support for PHP 8 which has no enums and b) we're using this package in a lot of our projects so we want to automatically have the transformer when using typescript-transformer.

**Comment by scaabel** [comment]
@rubenvanassche noted. Thanks.

**Comment by thewebartisan7** [comment]
It would be better to add a note in the documentation about this, as it took me some time to figure out why I got this error. Thanks!
