### ISSUE TITLE
@typescript annotation works but PHP8 attributes don't

### ISSUE THREAD

**Issue by mixmav** [spatie/laravel-typescript-transformer#29]
When I run the `php artisan typescript:transform` command,
```
<?php
/** @typescript */ <------------- This works
```
But
```
<?php
#[TypeScript] <------------- This doesn't work
```

There are no errors, it just generates an empty file.

In the `config/typescript-transformer.php`, there's a comment saying that the attribution the collector is looking for is `![TypeScript] `. I don't understand, however, because that's not a valid PHP class attribute. 

Would appreciate some clarification. And thanks for the amazing package!

**Comment by rubenvanassche** [comment]
Hi @mixmav, could you try this in a clean project? The comment is indeed incorrect, I've updated it. Also make sure you import the attribute correctly.

I'm gonna close this for know, because I'm quite sure this is still working. I've run TS transformer 5 minuten ago with those attributes and no problems.

If there's still a problem and it really appears to be a bug, please add a comment and we'll take a further look.
